package com.example.sourcenet.navigation

const val ROUT_SPLASH = "splash"
const val ROUT_LOGIN = "login"
const val ROUT_SIGNUP = "signup"
const val ROUT_HOME = "home"
const val ROUT_APPLY = "apply"
const val ROUT_BACKEND = "backend"
const val ROUT_CLOUD = "cloud"
const val ROUT_CYBER = "cyber"
const val ROUT_FRONTEND = "frontend"
const val ROUT_FULLSTACK = "fullstack"
const val ROUT_GRAPHICS = "graphics"
const val ROUT_TEST = "test"
const val ROUT_OTHERS = "other"
const val ROUT_SUCCESS = "success"